INSERT INTO PRODUCTS (NAME, PRICE) VALUES ('Lenovo laptop MSCHSD-81273678', 555888);
INSERT INTO PRODUCTS (NAME, PRICE) VALUES ('HP Dominator NaGiBaToR', 15000);
INSERT INTO PRODUCTS (NAME, PRICE) VALUES ('MacBook Pro, 1gb RAM, 1GHZ, 13inches', 999999999);
INSERT INTO PRODUCTS (NAME, PRICE) VALUES ('Huawei TotallyNotACloneOfIphone', 2000);
INSERT INTO PRODUCTS (NAME, PRICE) VALUES ('SberPortal', 15999);
INSERT INTO PRODUCTS (NAME, PRICE) VALUES ('Another Yandex IoT Device', 20999);
INSERT INTO PRODUCTS (NAME, PRICE) VALUES ('Another Yandex IoT Device ', 10888);